version: '3.8'

services:
  book_catalog:
    image: imeshaapp123.azurecr.io/book_catalog:latest
    build:
      context: ./book_catalog
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "postgresql://deakin_library_8vbn_user:peDid9S3Oo9b14FESRTa4KayAogGoeWy@dpg-cs2f28jqf0us73a6lj60-a.oregon-postgres.render.com/deakin_library_8vbn"

  inventory_management:
    image: imeshaapp123.azurecr.io/inventory_management:latest
    build:
      context: ./inventory_management
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: "postgresql://deakin_library_8vbn_user:peDid9S3Oo9b14FESRTa4KayAogGoeWy@dpg-cs2f28jqf0us73a6lj60-a.oregon-postgres.render.com/deakin_library_8vbn"