apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: bookcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcatalog
  template:
    metadata:
      labels:
        app: bookcatalog
    spec:
      containers:
        - name: bookcatalog
          image: imeshaapp123.azurecr.io/book_catalog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://deakin_library_8vbn_user:peDid9S3Oo9b14FESRTa4KayAogGoeWy@dpg-cs2f28jqf0us73a6lj60-a.oregon-postgres.render.com/deakin_library_8vbn"
---
apiVersion: v1
kind: Service
metadata:
  name: bookcatalog-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8000
      protocol: TCP
  selector:
    app: bookcatalog
