apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventorymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventorymanagement
  template:
    metadata:
      labels:
        app: inventorymanagement
    spec:
      containers:
        - name: inventorymanagement
          image: imeshaapp123.azurecr.io/inventory_management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://deakin_library_8vbn_user:peDid9S3Oo9b14FESRTa4KayAogGoeWy@dpg-cs2f28jqf0us73a6lj60-a.oregon-postgres.render.com/deakin_library_8vbn"
---
apiVersion: v1
kind: Service
metadata:
  name: inventorymanagement-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8000
      protocol: TCP
  selector:
    app: inventorymanagement
